[package]
name = "cityrade"
version = "0.1.0"
edition = "2024"

[dependencies]
cityrade-types = { path = "cityrade-types" }
cityrade-macros = { path = "cityrade-macros" }
dioxus = "0.6.3"
human-panic = "2.0.2"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
